name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.11"
        use-only-tar-bz2: true
        miniforge-version: latest
    - name: install dependencies
      run: |
        mamba update --all
        mamba install freecad numpy scipy pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
